/* golden_can_ford.h -- GENERATED by tools/make_can_golden.py; do not edit.
 * Golden CAN vectors for the Ford control-pack dialect (the 0x270-set).
 *
 * Frames were ENCODED with cantools from the repo's source of truth,
 * assets/can/ford-control-pack-gen4.dbc, itself transcribed from the
 * official Ford Performance tables: IS_M-6017-M50HM (Gen 4X, 09/16/24)
 * p.36 "CAN Message Definition" and IS_M-6017-73M (7.3L, 02/21/23)
 * s.12.0 p.29 (byte-identical tables),
 * performanceparts.ford.com/download/instructionsheets/.
 *
 * Expected channel values were computed inside the generator from the
 * spec constants (degF = degC*9/5+32, psi = kPa*0.145037738,
 * mph = km/h / 1.60934; rpm/AFR/volts pass through) -- never from the
 * C decoder, so the DBC encode and the dash_can_ford.h decode stay
 * independent transcriptions of the same tables (plan KTD8).
 */

#pragma once

#include <stdint.h>

#include "dash_data.h" /* DASH_CH_* ids; tests compile with -I MustangDash */

/* Per-channel quantization tolerances for parity bounds: one raw
 * quantum (DBC scaling) through the unit conversion. Derived once from
 * the spec -- NEVER widen; re-derive on any scaling change (KTD8). */
#define GOLDEN_CAN_TOL_RPM 1.0f /* 1 rpm/bit, pass-through */
#define GOLDEN_CAN_TOL_SPEED_MPH 0.0621372737f /* 0.1 km/h quantum -> mph */
#define GOLDEN_CAN_TOL_ECT_F 1.8f /* 1 degC quantum -> degF */
#define GOLDEN_CAN_TOL_OILT_F 1.8f /* 1 degC quantum -> degF */
#define GOLDEN_CAN_TOL_OILP_PSI 0.145037738f /* 1 kPa quantum -> psi */
#define GOLDEN_CAN_TOL_VOLTS 0.01f /* 0.01 V/bit, pass-through */
#define GOLDEN_CAN_TOL_AFR 0.01f /* 0.01 A/F per bit, both banks */
#define GOLDEN_CAN_TOL_FUELP_PSI 0.145037738f /* 1 kPa quantum -> psi */

/* Expected post-conversion outcome of decoding one vector.
 * expect_valid 1: the channel must be valid and match value within its
 * GOLDEN_CAN_TOL_* bound. expect_valid 0: the channel must be INVALID
 * after this frame (sentinel dead-front); value is 0 and unused. */
typedef struct {
    uint8_t ch;           /* DASH_CH_* id (dash_data.h) */
    uint8_t expect_valid;
    float value;          /* dash units: rpm/mph/degF/psi/V/AFR */
} GoldenCanExpect;

/* One raw frame plus its expectation slice in golden_can_expects[].
 * n_expect 0 = the frame must be IGNORED (DashState untouched). */
typedef struct {
    uint16_t id;          /* CAN identifier value */
    uint8_t ext;          /* 1 = 29-bit frame (identifier may spoof a
                             Ford id; the decoder must ignore it) */
    uint8_t dlc;
    uint8_t bytes[8];     /* dlc bytes meaningful; rest zero */
    uint8_t first_expect; /* index into golden_can_expects[] */
    uint8_t n_expect;
    const char *name;     /* for test diagnostics */
} GoldenCanVector;

#define GOLDEN_CAN_VECTOR_COUNT 21u
#define GOLDEN_CAN_EXPECT_COUNT 44u

static const GoldenCanExpect golden_can_expects[] = {
    /* [0..0] nominal_0270_rpm */
    { DASH_CH_RPM, 1u, 3500.0f },
    /* [1..3] nominal_0274_afr_fuelp */
    { DASH_CH_AFR_L, 1u, 12.6f },
    { DASH_CH_AFR_R, 1u, 12.1f },
    { DASH_CH_FUELP, 1u, 49.3128309f },
    /* [4..4] nominal_0275_speed */
    { DASH_CH_SPEED, 1u, 74.1919048f },
    /* [5..8] nominal_0278_temps */
    { DASH_CH_ECT, 1u, 194.0f },
    { DASH_CH_OILT, 1u, 176.0f },
    { DASH_CH_OILP, 1u, 49.3128309f },
    { DASH_CH_VOLTS, 1u, 13.3f },
    /* [9..9] min_0270 */
    { DASH_CH_RPM, 1u, 0.0f },
    /* [10..12] min_0274 */
    { DASH_CH_AFR_L, 1u, 7.0f },
    { DASH_CH_AFR_R, 1u, 7.0f },
    { DASH_CH_FUELP, 1u, 0.0f },
    /* [13..13] min_0275 */
    { DASH_CH_SPEED, 1u, 0.0f },
    /* [14..17] min_0278 */
    { DASH_CH_ECT, 1u, -40.0f },
    { DASH_CH_OILT, 1u, -40.0f },
    { DASH_CH_OILP, 1u, 0.0f },
    { DASH_CH_VOLTS, 1u, 0.0f },
    /* [18..18] max_0270 */
    { DASH_CH_RPM, 1u, 16383.0f },
    /* [19..21] max_0274 */
    { DASH_CH_AFR_L, 1u, 27.47f },
    { DASH_CH_AFR_R, 1u, 27.47f },
    { DASH_CH_FUELP, 1u, 74.1142841f },
    /* [22..22] max_0275 */
    { DASH_CH_SPEED, 1u, 254.452136f },
    /* [23..26] max_0278 */
    { DASH_CH_ECT, 1u, 419.0f },
    { DASH_CH_OILT, 1u, 419.0f },
    { DASH_CH_OILP, 1u, 148.373606f },
    { DASH_CH_VOLTS, 1u, 20.47f },
    /* [27..30] sentinel_ect_degraded */
    { DASH_CH_ECT, 0u, 0.0f },
    { DASH_CH_OILT, 1u, 176.0f },
    { DASH_CH_OILP, 1u, 49.3128309f },
    { DASH_CH_VOLTS, 1u, 13.3f },
    /* [31..34] sentinel_eot_faulted */
    { DASH_CH_ECT, 1u, 194.0f },
    { DASH_CH_OILT, 0u, 0.0f },
    { DASH_CH_OILP, 1u, 49.3128309f },
    { DASH_CH_VOLTS, 1u, 13.3f },
    /* [35..35] burst_0270 */
    { DASH_CH_RPM, 1u, 4800.0f },
    /* [36..38] burst_0274 */
    { DASH_CH_AFR_L, 1u, 12.5f },
    { DASH_CH_AFR_R, 1u, 12.4f },
    { DASH_CH_FUELP, 1u, 55.1143404f },
    /* [39..39] burst_0275 */
    { DASH_CH_SPEED, 1u, 74.937552f },
    /* [40..43] burst_0278 */
    { DASH_CH_ECT, 1u, 203.0f },
    { DASH_CH_OILT, 1u, 221.0f },
    { DASH_CH_OILP, 1u, 65.2669821f },
    { DASH_CH_VOLTS, 1u, 13.8f },
};

static const GoldenCanVector golden_can_vectors[] = {
    /* [0] nominal 0x270: 3500 rpm, raw 3500 -> bytes 0-1 = 0x0D 0xAC (the
     * known-good cross-check). ENGINE_SPEED_HZ = rpm/60 (raw 5833), MAN_VAC
     * = -30 kPa (raw 750), DI_PRESSURE = 11000 kPa: populated for bit-
     * masking realism, all undecoded. */
    { 0x270u, 0u, 8u,
      { 0x0Du, 0xACu, 0x2Du, 0x92u, 0x02u, 0xEEu, 0x2Au, 0xF8u },
      0u, 1u, "nominal_0270_rpm" },
    /* [1] nominal 0x274: AF0 raw 560 -> 12.6, AF1 raw 510 -> 12.1 (power
     * mixture), FUEL_PRESSURE 340 kPa, BOOST 0 (NA car, undecoded). */
    { 0x274u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x23u, 0x03u, 0xFDu, 0x54u, 0x00u },
      1u, 3u, "nominal_0274_afr_fuelp" },
    /* [2] nominal 0x275: VSPD raw 1194 = 119.4 km/h -> ~74.2 mph. */
    { 0x275u, 0u, 8u,
      { 0x4Au, 0xA0u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      4u, 1u, "nominal_0275_speed" },
    /* [3] nominal 0x278: ECT 90 degC -> 194 degF, EOT 80 degC -> 176 degF,
     * EOP 340 kPa -> psi, VBAT 13.30 V; TOT/SHIFTER/CODES/GEAR populated
     * but undecoded. */
    { 0x278u, 0u, 8u,
      { 0x82u, 0x78u, 0x7Du, 0x55u, 0x04u, 0x00u, 0xA6u, 0x43u },
      5u, 4u, "nominal_0278_temps" },
    /* [4] min edge 0x270: all-zero raw. RPM 0; MAN_VAC raw 0 would be -105
     * kPa but is undecoded, just 0 raw here. */
    { 0x270u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      9u, 1u, "min_0270" },
    /* [5] min edge 0x274: all-zero raw. AFR floor is the +7 offset (raw 0
     * -> 7.0 A/F, not zero); FUELP 0 kPa -> 0 psi. */
    { 0x274u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      10u, 3u, "min_0274" },
    /* [6] min edge 0x275: VSPD raw 0 -> 0 mph. */
    { 0x275u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      13u, 1u, "min_0275" },
    /* [7] min edge 0x278: all-zero raw. ECT/EOT raw 0 = -40 degC = -40 degF
     * (valid, NOT a sentinel); EOP 0 psi; VBAT 0.00 V. */
    { 0x278u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      14u, 4u, "min_0278" },
    /* [8] max edge 0x270: every signal at raw max -- RPM 16383 plus
     * saturated undecoded neighbors, so a decoder mask slip reads garbage
     * instead of zeros. */
    { 0x270u, 0u, 8u,
      { 0x3Fu, 0xFFu, 0x7Fu, 0xFEu, 0x0Fu, 0xFFu, 0x7Fu, 0xFFu },
      18u, 1u, "max_0270" },
    /* [9] max edge 0x274: AF0/AF1 raw 2047 -> 27.47 A/F, FUEL_PRESSURE 511
     * kPa, BOOST raw max 511 (undecoded). */
    { 0x274u, 0u, 8u,
      { 0x00u, 0x00u, 0xFFu, 0xFFu, 0xFFu, 0xFFu, 0xFFu, 0x00u },
      19u, 3u, "max_0274" },
    /* [10] max edge 0x275: VSPD raw 4095 = 409.5 km/h -> ~254.5 mph. */
    { 0x275u, 0u, 8u,
      { 0xFFu, 0xF0u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      22u, 1u, "max_0275" },
    /* [11] max edge 0x278: ECT/EOT raw 255 = 215 degC = 419 degF -- ABOVE
     * the 214/215 sentinel bytes, must convert, not invalidate (KTD3: only
     * raw 214/215 dead-front). EOP raw 1023 kPa, VBAT raw 2047 -> 20.47 V,
     * others at raw max. */
    { 0x278u, 0u, 8u,
      { 0xFFu, 0xFFu, 0xFFu, 0xFFu, 0xCFu, 0xFFu, 0xFFu, 0xEFu },
      23u, 4u, "max_0278" },
    /* [12] sentinel: ECT raw 214 (byte 0 = 0xD6, physical 174 degC =
     * 'sensor degraded') -> DASH_CH_ECT must be INVALID, never converted;
     * EOT/EOP/VBAT in the SAME frame stay valid. */
    { 0x278u, 0u, 8u,
      { 0xD6u, 0x78u, 0x7Du, 0x55u, 0x04u, 0x00u, 0xA6u, 0x43u },
      27u, 4u, "sentinel_ect_degraded" },
    /* [13] sentinel: EOT raw 215 (byte 1 = 0xD7, physical 175 degC =
     * 'sensor faulted') -> DASH_CH_OILT must be INVALID; ECT/EOP/VBAT in
     * the SAME frame stay valid. */
    { 0x278u, 0u, 8u,
      { 0x82u, 0xD7u, 0x7Du, 0x55u, 0x04u, 0x00u, 0xA6u, 0x43u },
      31u, 4u, "sentinel_eot_faulted" },
    /* [14] unknown ID 0x123: not in the dialect, must be ignored (state
     * untouched). */
    { 0x123u, 0u, 8u,
      { 0x11u, 0x22u, 0x33u, 0x44u, 0x55u, 0x66u, 0x77u, 0x88u },
      35u, 0u, "unknown_id_0x123" },
    /* [15] short DLC: 0x270 with dlc 4 (first 4 bytes of a 6000 rpm frame),
     * must be ignored -- a truncated frame proves nothing about any signal. */
    { 0x270u, 0u, 4u,
      { 0x17u, 0x70u, 0x4Eu, 0x20u, 0x00u, 0x00u, 0x00u, 0x00u },
      35u, 0u, "short_dlc_0270" },
    /* [16] extended-ID spoof: 29-bit frame whose identifier VALUE is 0x270
     * (7250 rpm payload), must be ignored -- the dialect is 11-bit only,
     * and the global filter otherwise admits it. */
    { 0x270u, 1u, 8u,
      { 0x1Cu, 0x52u, 0x5Eu, 0x66u, 0x04u, 0x1Au, 0x2Eu, 0xE0u },
      35u, 0u, "ext_id_spoof_0270" },
    /* [17] burst 1/4 (corner exit, consistent instant): 4800 rpm; HZ =
     * 80.00 (raw 8000); MAN_VAC -2 kPa near-WOT (raw 1030); DI 12000 kPa. */
    { 0x270u, 0u, 8u,
      { 0x12u, 0xC0u, 0x3Eu, 0x80u, 0x04u, 0x06u, 0x2Eu, 0xE0u },
      35u, 1u, "burst_0270" },
    /* [18] burst 2/4: AF0 12.5 / AF1 12.4 under load, fuel 380 kPa. */
    { 0x274u, 0u, 8u,
      { 0x00u, 0x00u, 0x00u, 0x22u, 0x64u, 0x39u, 0x7Cu, 0x00u },
      36u, 3u, "burst_0274" },
    /* [19] burst 3/4: 120.6 km/h (raw 1206) -> ~74.9 mph, consistent with
     * 4800 rpm in 3rd (3.73 final, 315/30R18). */
    { 0x275u, 0u, 8u,
      { 0x4Bu, 0x60u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      39u, 1u, "burst_0275" },
    /* [20] burst 4/4: ECT 95 degC -> 203 degF, EOT 105 degC -> 221 degF
     * (oil hotter than coolant on track), EOP 450 kPa, VBAT 13.80 V, 3rd
     * gear. */
    { 0x278u, 0u, 8u,
      { 0x87u, 0x91u, 0x82u, 0x70u, 0x84u, 0x00u, 0xACu, 0x83u },
      40u, 4u, "burst_0278" },
};

_Static_assert(sizeof golden_can_vectors / sizeof golden_can_vectors[0]
                   == GOLDEN_CAN_VECTOR_COUNT,
               "vector count drifted");
_Static_assert(sizeof golden_can_expects / sizeof golden_can_expects[0]
                   == GOLDEN_CAN_EXPECT_COUNT,
               "expect count drifted");

/* Vector summary:
 * [ 0] nominal_0270_rpm       0x270     dlc=8  0d ac 2d 92 02 ee 2a f8
 *       -> RPM=3500
 * [ 1] nominal_0274_afr_fuelp 0x274     dlc=8  00 00 00 23 03 fd 54 00
 *       -> AFR_L=12.6 AFR_R=12.1 FUELP=49.3128
 * [ 2] nominal_0275_speed     0x275     dlc=8  4a a0 00 00 00 00 00 00
 *       -> SPEED=74.1919
 * [ 3] nominal_0278_temps     0x278     dlc=8  82 78 7d 55 04 00 a6 43
 *       -> ECT=194 OILT=176 OILP=49.3128 VOLTS=13.3
 * [ 4] min_0270               0x270     dlc=8  00 00 00 00 00 00 00 00
 *       -> RPM=0
 * [ 5] min_0274               0x274     dlc=8  00 00 00 00 00 00 00 00
 *       -> AFR_L=7 AFR_R=7 FUELP=0
 * [ 6] min_0275               0x275     dlc=8  00 00 00 00 00 00 00 00
 *       -> SPEED=0
 * [ 7] min_0278               0x278     dlc=8  00 00 00 00 00 00 00 00
 *       -> ECT=-40 OILT=-40 OILP=0 VOLTS=0
 * [ 8] max_0270               0x270     dlc=8  3f ff 7f fe 0f ff 7f ff
 *       -> RPM=16383
 * [ 9] max_0274               0x274     dlc=8  00 00 ff ff ff ff ff 00
 *       -> AFR_L=27.47 AFR_R=27.47 FUELP=74.1143
 * [10] max_0275               0x275     dlc=8  ff f0 00 00 00 00 00 00
 *       -> SPEED=254.452
 * [11] max_0278               0x278     dlc=8  ff ff ff ff cf ff ff ef
 *       -> ECT=419 OILT=419 OILP=148.374 VOLTS=20.47
 * [12] sentinel_ect_degraded  0x278     dlc=8  d6 78 7d 55 04 00 a6 43
 *       -> ECT=INVALID OILT=176 OILP=49.3128 VOLTS=13.3
 * [13] sentinel_eot_faulted   0x278     dlc=8  82 d7 7d 55 04 00 a6 43
 *       -> ECT=194 OILT=INVALID OILP=49.3128 VOLTS=13.3
 * [14] unknown_id_0x123       0x123     dlc=8  11 22 33 44 55 66 77 88
 *       -> (must be ignored; DashState untouched)
 * [15] short_dlc_0270         0x270     dlc=4  17 70 4e 20 00 00 00 00
 *       -> (must be ignored; DashState untouched)
 * [16] ext_id_spoof_0270      0x270 EXT dlc=8  1c 52 5e 66 04 1a 2e e0
 *       -> (must be ignored; DashState untouched)
 * [17] burst_0270             0x270     dlc=8  12 c0 3e 80 04 06 2e e0
 *       -> RPM=4800
 * [18] burst_0274             0x274     dlc=8  00 00 00 22 64 39 7c 00
 *       -> AFR_L=12.5 AFR_R=12.4 FUELP=55.1143
 * [19] burst_0275             0x275     dlc=8  4b 60 00 00 00 00 00 00
 *       -> SPEED=74.9376
 * [20] burst_0278             0x278     dlc=8  87 91 82 70 84 00 ac 83
 *       -> ECT=203 OILT=221 OILP=65.267 VOLTS=13.8
 */
