/*
 * splash_config.h - splash theme selection.
 *
 * ONE THEME SHIPS (2026-08-21). Red and checkered were retired along with the
 * authored 1024x600 backgrounds: at 614,400 B each those overflowed RAM_G once
 * the dash fonts grew, and carrying all three cost ~888 KB of MCU flash for
 * assets only one of which could ever play. Blue is the car.
 *
 * The background is no longer an authored bitmap at all -- it is a seamless
 * machined tile plus a cluster-wide glow, both generated by
 * tools/make_material.py, which is where the reasoning lives.
 *
 * A future CAN-selected theme (discussed 2026-08-21, not built) would restore
 * a table here. It costs no extra RAM_G -- staging is per-theme and only one
 * is ever resident -- but every theme it can choose between must be present in
 * MCU flash, so the ~888 KB reclaimed above is what such a feature would spend.
 */

#ifndef SPLASH_CONFIG_H
#define SPLASH_CONFIG_H

#define SPLASH_THEME_BLUE 0

#if !defined(SPLASH_THEME)
#define SPLASH_THEME SPLASH_THEME_BLUE
#endif

#if (SPLASH_THEME != SPLASH_THEME_BLUE)
#error "SPLASH_THEME must be SPLASH_THEME_BLUE -- red and checkered were retired 2026-08-21"
#endif

#endif /* SPLASH_CONFIG_H */
