#!/usr/bin/env python3
"""Generate JLCPCB-ready BOM and CPL from the KiCad project, and report coverage.

The interesting part is the field mapping. Board3's parts came from EasyEDA
carrying full supplier identity, and the import preserved it -- but under
EasyEDA's field names ("LCSC Part Name", "Manufacturer Part") rather than the
conventional ones. Tools that look for a field literally named MPN therefore
report zero coverage on a fully-sourced board: kicad-happy's SS-001 called it
"0/48 unique parts" and flagged the board as not pre-fab ready, when 49 of 50
grouped BOM lines actually carry both an LCSC number and a manufacturer part.

So this maps rather than sources. Nothing here looks parts up; it reads what is
already in the schematic and emits it under the column names JLCPCB expects.

  python tools/kicad_fab.py kicad/board3/ --out fab/

Rotation: this tool emits KiCad's value UNMODIFIED, and for Board3 that is
correct. Verified 2026-07-27, and worth understanding before anyone "fixes" it.

KiCad and JLCPCB disagree about a footprint's zero rotation, which is why the
kicad-jlcpcb-tools plugin ships a correction table (^LQFP- +270, ^SOIC- +270,
^SOT-23 -90, ...). Those corrections are calibrated against KiCad's OFFICIAL
library. Board3's footprints came from EasyEDA, and measuring both libraries'
pin-1 datums shows EasyEDA draws these packages a quarter turn from KiCad's:

  package    EasyEDA pin 1   KiCad stock pin 1   plugin C   C for this board
  LQFP-144   south-west      north-west            +270            0
  SOIC-8     south-west      north-west            +270            0
  SOT-23-6   south-west      north-west             -90            0

Three package families, two different plugin values, all resolving to zero --
because EasyEDA/LCSC footprints are already drawn to JLC's own datum, which is
what you would hope from the ecosystem that assembles the board.

THE TRAP: the plugin matches on footprint NAME, and Board3's names still start
with "LQFP-", "SOIC-", "SOT-23". Running its fabrication export against this
project would match those rules and rotate the parts a quarter turn that they do
not need -- a board full of backwards ICs, generated by the tool you reached for
to prevent exactly that. If you use the plugin here, add per-footprint overrides
first. See docs/plans/2026-07-27-002 U9 for the full derivation.
"""

from __future__ import annotations

import argparse
import csv
import math
import zipfile
import subprocess
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).parent

EXIT_OK = 0
EXIT_ERROR = 1
EXIT_INCOMPLETE = 2

# EasyEDA's field names on the left, what we emit on the right. Extend this
# rather than renaming fields in the schematic -- the schematic is the design,
# and editing it to satisfy a downstream tool's naming convention risks the
# netlist for a cosmetic gain.
#
# The LCSC code lives in "Supplier Part" (C14663, C116592...). NOT in
# "LCSC Part Name", which despite its name holds descriptive text, often in
# Chinese -- "0805 白灯 高亮" is a description of an 0805 white LED, not a
# part number. Mapping the obvious-looking field produced a BOM whose LCSC
# column contained footprint names and capacitor values, and it looked fine
# in aggregate because every row was populated.
#
# "JLCPCB Part Class" is Basic vs Extended, which drives assembly cost --
# Extended parts carry a per-reel loading fee, so it belongs in a BOM someone
# is about to quote.
BOM_FIELDS = ("Reference,Value,Footprint,${QUANTITY},Supplier Part,"
              "Manufacturer Part,Manufacturer,JLCPCB Part Class")
BOM_LABELS = "Designator,Comment,Footprint,Quantity,LCSC,MPN,Manufacturer,Part Class"
BOM_GROUP_BY = "Value,Footprint,Supplier Part"

# Parts whose datasheet orientation is unambiguous, so a rotation error shows up
# as an obviously wrong pad-1 corner rather than a subtle one. U1 is the 144-pin
# LQFP everything else hangs off, U2 the WSON-8 flash, D9 a SOT-23-6, USBC1 the
# connector whose orientation is mechanically constrained by the board edge.
ROTATION_WITNESSES = ("U1", "U2", "D9", "USBC1", "U8")


def _cli() -> str:
    sys.path.insert(0, str(HERE))
    from kicad_env import find_kicad_cli  # reuse U1's resolver; never hardcode

    return str(find_kicad_cli())


def _run(*args: str) -> subprocess.CompletedProcess:
    proc = subprocess.run([_cli(), *args], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"kicad-cli {' '.join(args[:3])} failed: {proc.stderr.strip()[:400]}")
    return proc


def find_project(target: Path) -> tuple[Path, Path]:
    """Resolve a project directory to (schematic, board). Ambiguity is an error."""
    project = target if target.is_dir() else target.parent
    schs = sorted(project.glob("*.kicad_sch"))
    pcbs = sorted(project.glob("*.kicad_pcb"))
    if len(schs) != 1 or len(pcbs) != 1:
        raise RuntimeError(
            f"expected exactly one .kicad_sch and one .kicad_pcb in {project}; "
            f"found {len(schs)} and {len(pcbs)}"
        )
    return schs[0], pcbs[0]


def export_bom(schematic: Path, out: Path) -> list[dict]:
    # --ref-range-delimiter "" disables reference ranges. The default collapses
    # consecutive refs into "C3-C5", which JLCPCB's upload parser treats as one
    # literal designator that matches nothing in the CPL -- the site rejects the
    # pair outright ("The BOM file doesn't match the CPL file").
    proc = _run("sch", "export", "bom",
                "--fields", BOM_FIELDS, "--labels", BOM_LABELS,
                "--group-by", BOM_GROUP_BY, "--exclude-dnp",
                "--ref-range-delimiter", "",
                "-o", str(out), str(schematic))
    # kicad-cli reports annotation problems on stdout rather than failing. An
    # unannotated symbol reaches the BOM as designator "?" and cannot be ordered.
    if "annotation" in (proc.stdout + proc.stderr).lower():
        print("  WARNING: schematic has annotation errors -- see unplaceable rows below",
              flush=True)
    return list(csv.DictReader(out.open(encoding="utf-8-sig")))


def export_cpl(board: Path, out: Path) -> list[dict]:
    """Export placement, then drop entries that are not placeable components.

    The raw export includes free pads carried over from the import -- rows with
    an empty Ref and a package like "Pad_e673". They are board features, not
    parts, and an assembler fed them would try to place something that does not
    exist. Filtering here rather than trusting the export is the point.
    """
    _run("pcb", "export", "pos", "--format", "csv", "--units", "mm",
         "--side", "both", "--exclude-dnp", "-o", str(out), str(board))
    rows = list(csv.DictReader(out.open(encoding="utf-8-sig")))
    placeable = [r for r in rows if (r.get("Ref") or "").strip()]
    dropped = len(rows) - len(placeable)
    if dropped:
        with out.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(placeable)
        print(f"  dropped {dropped} non-component row(s) from CPL (free pads, no Ref)",
              flush=True)
    return placeable


def export_gerbers(board: Path, outdir: Path) -> list:
    """Gerbers + Excellon drills for a 4-layer JLCPCB order.

    The layer list is explicit rather than "whatever the board has". A board that
    silently gained or lost a layer would otherwise produce a plausible-looking
    package that is wrong in a way nobody notices until the fab asks.
    """
    gerber_dir = outdir / "gerbers"
    gerber_dir.mkdir(parents=True, exist_ok=True)
    # Clear previous output first. Gerbers are named per layer, so a run that
    # renames or drops a layer would otherwise leave the old file sitting in the
    # package -- and a fab reads what is in the folder, not what you meant.
    for stale in gerber_dir.glob("*"):
        if stale.suffix.lower() in (".gbr", ".gbrjob", ".drl") and stale.is_file():
            stale.unlink()
    layers = ("F.Cu,In1.Cu,In2.Cu,B.Cu,"
              "F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,"
              "F.Mask,B.Mask,Edge.Cuts")
    _run("pcb", "export", "gerbers", "--layers", layers,
         "--no-protel-ext", "--subtract-soldermask",
         "-o", str(gerber_dir) + "/", str(board))
    _run("pcb", "export", "drill", "--format", "excellon",
         "--drill-origin", "absolute", "--excellon-units", "mm",
         "--generate-map", "--map-format", "gerberx2",
         "-o", str(gerber_dir) + "/", str(board))
    canonicalise_gerber_names(board, gerber_dir)
    files = sorted(p for p in gerber_dir.iterdir() if p.is_file())
    # JLCPCB takes a zip, not a folder, so ship the thing that can be uploaded.
    archive = outdir / "gerbers-jlcpcb.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in files:
            zf.write(f, f.name)
    return files


def canonicalise_gerber_names(board: Path, gerber_dir: Path) -> list:
    """Rename exported gerbers from the board's layer names to KiCad's canonical ones.

    KiCad names each gerber after the layer's USER name, and Board3's user names
    came from EasyEDA via the importer. Most are merely verbose ("Top Solder Mask
    Layer"), but one is a trap: Edge.Cuts is named "Multi-Layer", so the board
    OUTLINE ships as `...-Multi-Layer.gbr`. In Altium and EasyEDA vocabulary
    "multi-layer" means copper present on every layer -- a pad property, not an
    outline -- so a fab reading that filename learns the opposite of the truth,
    and a package with no recognisable outline is a quote that comes back as a
    question at best.

    The gerbers are a derived artifact, so renaming them is safe in a way that
    renaming the board's layers would not be.
    """
    try:
        import pcbnew
    except ImportError:
        print("  NOTE: pcbnew unavailable -- gerbers keep the board's own layer "
              "names, including Edge.Cuts as 'Multi-Layer'", flush=True)
        return []

    pcb = pcbnew.LoadBoard(str(board))
    renames = []
    for lid in range(pcbnew.PCB_LAYER_ID_COUNT):
        if not pcb.IsLayerEnabled(lid):
            continue
        user, canon = pcb.GetLayerName(lid), pcbnew.LayerName(lid)
        if user == canon:
            continue
        for path in list(gerber_dir.iterdir()):
            if path.name.endswith(f"-{user}.gbr"):
                target = path.with_name(path.name[: -len(f"-{user}.gbr")]
                                        + f"-{canon.replace('.', '_')}.gbr")
                path.rename(target)
                renames.append((user, target.name))
    for user, name in renames:
        print(f"  renamed gerber: {user!r} -> {name.rsplit('-', 1)[-1]}", flush=True)
    return renames


def check_gerber_layers(files: list) -> list:
    """Every layer the 4-layer stackup needs must be present, and named."""
    required = {
        "F_Cu": "top copper", "In1_Cu": "inner 1 (GND plane)",
        "In2_Cu": "inner 2 (+5V plane)", "B_Cu": "bottom copper",
        "F_Mask": "top mask", "B_Mask": "bottom mask",
        "F_Silkscreen": "top silk", "B_Silkscreen": "bottom silk",
        "F_Paste": "top paste", "B_Paste": "bottom paste",
        "Edge_Cuts": "board outline",
    }
    names = " ".join(f.name for f in files)
    missing = [f"{key} ({what})" for key, what in required.items() if key not in names]
    if not any(f.suffix.lower() == ".drl" for f in files):
        missing.append("Excellon drill file (.drl)")
    return missing


def rotation_audit(board: Path, refs: tuple) -> list:
    """Where does pad 1 actually sit, for parts whose datasheet orientation is known?

    KiCad's CPL rotation is measured against the FOOTPRINT's own zero, and JLCPCB
    assembles against THEIR library's zero. The two agree only when the footprint
    was drawn to the same convention, and when they disagree the failure mode is
    a board full of backwards parts with no warning anywhere in the flow.

    This does not claim to know JLC's convention. It reports the ground truth an
    assembler can check against: the placement angle the CPL carries, and the
    compass direction of pad 1 from the body centre as the board actually draws
    it. If those disagree with the datasheet, stop before ordering assembly.
    """
    try:
        import pcbnew
    except ImportError:
        return [("(skipped)", "pcbnew unavailable -- re-run under KiCad's own "
                              "interpreter to audit rotation")]

    pcb = pcbnew.LoadBoard(str(board))
    out = []
    for fp in pcb.GetFootprints():
        ref = fp.GetReference()
        if ref not in refs:
            continue
        pad1 = next((p for p in fp.Pads() if p.GetNumber() in ("1", "A1")), None)
        if pad1 is None:
            continue
        centre, pos = fp.GetPosition(), pad1.GetPosition()
        dx, dy = (pos.x - centre.x) / 1e6, (pos.y - centre.y) / 1e6
        theta = math.radians(fp.GetOrientationDegrees())
        # De-rotate into the footprint's OWN frame. This is the number that
        # matters: it is the library's definition of zero degrees, and it is what
        # has to agree with JLCPCB's library for the CPL rotation to mean the
        # same thing at both ends. KiCad's positive rotation is anticlockwise on
        # screen while y grows downward, hence the sign pattern.
        lx = dx * math.cos(theta) - dy * math.sin(theta)
        ly = dx * math.sin(theta) + dy * math.cos(theta)
        out.append((ref, f"rot {fp.GetOrientationDegrees():+7.1f} deg | pad 1 on board: "
                         f"{_compass(dx, dy):<10} | at the footprint's own 0 deg: "
                         f"{_compass(lx, ly)}"))
    return out


def _compass(dx: float, dy: float) -> str:
    """Board frame: +x east, +y SOUTH -- KiCad's y grows downward."""
    vertical = "north" if dy < -0.05 else ("south" if dy > 0.05 else "")
    horizontal = "east" if dx > 0.05 else ("west" if dx < -0.05 else "")
    return "-".join(p for p in (vertical, horizontal) if p) or "centre"


# Symbols that turn up in EasyEDA-authored values, mapped to the ASCII spelling
# an English-language BOM would use anyway. Anything not listed is stripped by
# _ascii() rather than guessed at.
_ASCII_SUBS = {
    "Ω": "",      # GREEK CAPITAL OMEGA -- "10kOhm" reads worse than "10k"
    "Ω": "",      # OHM SIGN, the other codepoint for the same glyph
    "µ": "u",     # MICRO SIGN
    "μ": "u",     # GREEK SMALL MU -- visually identical, different codepoint
    "°": "deg",
    "℃": "C",
    "±": "+/-",
    "–": "-",     # EN DASH
    "—": "-",     # EM DASH
    "‘": "'", "’": "'",
    "“": '"', "”": '"',
}


def _ascii(value: str) -> str:
    """Coerce a field to pure ASCII for the vendor upload.

    JLCPCB's uploader does not declare an encoding and these files carry no BOM
    marker, so a non-ASCII byte is read under whatever the server guesses --
    cp1252 or GBK -- and the request dies with a 500 that names nothing. The
    values that trip it here are resistor legends written with a real Omega
    (10kOhm, 4.7kOhm) by the EasyEDA import.

    This project has already paid for this exact character once: freerouting's
    DSN reader pops a modal warning dialog on any non-ASCII byte, and the Omega
    in these same resistor values is what triggered it (CLAUDE.md, autorouting
    notes). Two tools, one codepoint.

    Substitutions come from _ASCII_SUBS; anything else outside ASCII is dropped
    after an NFKD pass, which folds accents rather than deleting the letter.
    """
    if not value:
        return ""
    for bad, good in _ASCII_SUBS.items():
        value = value.replace(bad, good)
    value = unicodedata.normalize("NFKD", value)
    return value.encode("ascii", "ignore").decode("ascii").strip()


def write_jlc_csvs(bom: list, cpl: list, outdir: Path) -> tuple:
    """Re-emit BOM and CPL under JLCPCB's own column names and order.

    The rich bom.csv is for quoting and for humans; these two are what gets
    uploaded. JLC's parser is tolerant about column ORDER but not about a CPL
    whose header says "Ref,PosX,PosY,Rot,Side" -- the fields it wants are
    Designator, Mid X, Mid Y, Layer and Rotation.
    """
    bom_path, cpl_path = outdir / "bom-jlcpcb.csv", outdir / "cpl-jlcpcb.csv"
    with bom_path.open("w", newline="", encoding="ascii") as fh:
        w = csv.writer(fh)
        w.writerow(["Comment", "Designator", "Footprint", "LCSC Part #"])
        for r in bom:
            w.writerow([_ascii(r.get("Comment", "")), _ascii(r.get("Designator", "")),
                        _ascii(r.get("Footprint", "")), _ascii(r.get("LCSC", ""))])
    with cpl_path.open("w", newline="", encoding="ascii") as fh:
        w = csv.writer(fh)
        w.writerow(["Designator", "Mid X", "Mid Y", "Layer", "Rotation"])
        for r in cpl:
            w.writerow([_ascii(r.get("Ref", "")), _ascii(r.get("PosX", "")),
                        _ascii(r.get("PosY", "")),
                        _ascii((r.get("Side", "") or "").capitalize()),
                        _ascii(r.get("Rot", ""))])
    return bom_path, cpl_path


def bom_cpl_symmetry(bom: list[dict], cpl: list[dict]) -> tuple[list[str], list[str]]:
    """Return (in BOM but not CPL, in CPL but not BOM). Either is unorderable.

    JLCPCB checks this on upload and refuses the pair -- "The below parts won't
    be assembled due to data missing ... designators don't exist in the CPL
    file". It is worth catching here because the two files come from DIFFERENT
    sources and can disagree while each is internally valid: the BOM is exported
    from the schematic, the CPL from the board. Both exports pass --exclude-dnp,
    so a part flagged Do-Not-Populate on ONLY one side is silently dropped from
    that file alone.

    That is not hypothetical. Commit 3c9f8c1 -- a GUI "Update PCB from Schematic"
    run, the one link in the workflow nothing can verify automatically (KTD12) --
    set DNP on 16 board footprints the schematic never marked: the eight
    telltales, both AW9523B expanders, and their decoupling. Every local check
    passed and DRC was 0/0. The defect surfaced only when JLCPCB's uploader
    rejected the package, and clicking past that dialog would have fabricated a
    board with its entire telltale subsystem unpopulated.

    A reference-range delimiter mismatch produces the same rejection by a
    different route; see export_bom. Two causes, one gate.
    """
    def refs(rows: list[dict], key: str) -> set:
        out = set()
        for r in rows:
            for d in (r.get(key) or "").split(","):
                d = d.strip()
                if d:
                    out.add(d)
        return out

    bom_refs = refs(bom, "Designator")
    cpl_refs = refs(cpl, "Ref")
    return sorted(bom_refs - cpl_refs), sorted(cpl_refs - bom_refs)


def coverage_report(bom: list[dict]) -> tuple[list[dict], list[dict]]:
    """Return (rows lacking any supplier identity, rows that cannot be placed)."""
    unsourced = [r for r in bom
                 if not (r.get("LCSC") or "").strip() and not (r.get("MPN") or "").strip()]
    unplaceable = [r for r in bom if "?" in (r.get("Designator") or "")
                   or not (r.get("Designator") or "").strip()]
    return unsourced, unplaceable


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("target", help="KiCad project directory (or any file inside it)")
    ap.add_argument("--out", default="fab", help="Output directory for BOM and CPL")
    args = ap.parse_args()

    try:
        schematic, board = find_project(Path(args.target))
    except RuntimeError as exc:
        print(f"fab export failed: {exc}", file=sys.stderr)
        return EXIT_ERROR

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)

    try:
        bom = export_bom(schematic, outdir / "bom.csv")
        cpl = export_cpl(board, outdir / "cpl.csv")
        gerbers = export_gerbers(board, outdir)
    except RuntimeError as exc:
        print(f"fab export failed: {exc}", file=sys.stderr)
        return EXIT_ERROR

    missing_layers = check_gerber_layers(gerbers)

    no_cpl, no_bom = bom_cpl_symmetry(bom, cpl)
    unsourced, unplaceable = coverage_report(bom)
    sourced = len(bom) - len(unsourced)

    print(f"schematic   : {schematic.name}")
    print(f"board       : {board.name}")
    print(f"BOM lines   : {len(bom)}  ({sourced} sourced, {len(unsourced)} without LCSC or MPN)")
    print(f"CPL rows    : {len(cpl)}")
    if no_cpl or no_bom:
        print("  BOM/CPL   : MISMATCH -- JLCPCB will refuse this pair on upload")
        if no_cpl:
            print(f"    in BOM, absent from CPL ({len(no_cpl)}): {', '.join(no_cpl)}")
            print("      -> usually DNP set on the BOARD footprint but not the schematic "
                  "symbol; check with pcbnew's IsDNP(), not by reading the file as text")
        if no_bom:
            print(f"    in CPL, absent from BOM ({len(no_bom)}): {', '.join(no_bom)}")
            print("      -> usually DNP set on the schematic SYMBOL but not the board "
                  "footprint, or a symbol with no supplier fields")
    else:
        print(f"  BOM/CPL   : symmetric ({len(cpl)} designators in both)")
    print(f"gerbers     : {len(gerbers)} file(s) in {outdir / 'gerbers'}")
    if missing_layers:
        print("  MISSING   : " + "; ".join(missing_layers))
    else:
        print("  layer set : complete for a 4-layer order (copper x4, mask, silk, "
              "paste, edge cuts, drills)")
    jlc_bom, jlc_cpl = write_jlc_csvs(bom, cpl, outdir)
    print(f"written     : {outdir / 'bom.csv'}, {outdir / 'cpl.csv'}")
    print(f"              {jlc_bom}, {jlc_cpl}  (JLCPCB column names)")

    print("\nrotation audit (check these against the datasheets before assembly):")
    for ref, detail in rotation_audit(board, ROTATION_WITNESSES):
        print(f"   {ref:<8} {detail}")

    for label, rows in (("NOT SOURCED", unsourced), ("NOT PLACEABLE", unplaceable)):
        if rows:
            print(f"\n{label} ({len(rows)}):", flush=True)
            for r in rows:
                print("   designator=%-14r value=%-20r footprint=%r" % (
                    r.get("Designator", ""), (r.get("Comment") or "")[:20],
                    (r.get("Footprint") or "")[:38]), flush=True)

    print("\nRotation is emitted as KiCad reports it, which is CORRECT here: Board3's\n"
          "EasyEDA footprints already use JLCPCB's datum (verified 2026-07-27 -- the\n"
          "module docstring shows the derivation). Do NOT apply kicad-jlcpcb-tools'\n"
          "corrections to this project: its rules match on names like 'LQFP-' and would\n"
          "rotate these parts a quarter turn they do not need.", flush=True)

    # A BOM/CPL mismatch is an ERROR, not INCOMPLETE: the package is not merely
    # short of information, it is one JLCPCB rejects outright -- or worse, one an
    # operator clicks past into a board assembled with parts missing.
    if no_cpl or no_bom:
        return EXIT_ERROR
    return EXIT_INCOMPLETE if (unsourced or unplaceable) else EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
